artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: give the url of the dataset where it is store
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion